### ISSUE TITLE
unknown package "LeanCopilot"

### ISSUE THREAD

**Issue by Peterjsr** [lean-dojo/LeanCopilot#100]
I followed the instruction: modified lakefile and typed  commands in the terminal, but still failed to set up. (Ubuntu 24.04)
![Screenshot from 2024-07-20 19-32-27](https://github.com/user-attachments/assets/11f9beba-f3de-4b19-8e65-f7810ce08bb3)
![Screenshot from 2024-07-20 19-34-46](https://github.com/user-attachments/assets/e6d2da83-516b-4c6b-8492-8e7b5674ec16)

**Comment by Peiyang-Song** [comment]
Hi @Peterjsr, I just tried Lean Copilot on my Linux machine. Mine is Ubuntu 22.04 (slightly different from your version but I don't think that would create much difference) and was not able to reproduce your error. It seems that both `lake update` and `lake build` did succeed on your end, and it's just `lake exe LeanCopilot/download` that created an error. Are you able to download our models directly from HuggingFace?

**Comment by Peiyang-Song** [comment]
Since all the crucial steps (e.g. `lake update` and `lake build`) did succeed, after downloading the models (either manually or by running `lake exe LeanCopilot/download`) Lean Copilot should be working. Feel free to reopen this issue if any difficulties are encountered.
