### ISSUE TITLE
Proof Suggestion Format Issue

### ISSUE THREAD

**Issue by yangky11** [lean-dojo/LeanCopilot#63]
It looks like there are some spurious newlines, probably due to updates to Lean's functions for displaying tactic suggestions.

https://github.com/yangky11/lean4-example/tree/ml4tp-tutorial

<img width="993" alt="image" src="https://github.com/lean-dojo/LeanCopilot/assets/5431913/a4b6d398-d44e-4f92-9916-20bc950803d2">

**Comment by Peiyang-Song** [comment]
Fixed the formatting issue for `suggest_tactics` in PR #64 .

**Comment by Peiyang-Song** [comment]
The rest of this issue is related to `aesop`. See Zulip discussion at https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Aesop.20script.20.28.60aesop.3F.60.29.20formatting.20issue.

I believe once this is fixed in `aesop` everything should be fine.

**Comment by Peiyang-Song** [comment]
Closing this issue as there's no more to be done on the LeanCopilot side.
