### ISSUE TITLE
the Lean language server could not connect

### ISSUE THREAD

**Issue by whsm** [lean-dojo/LeanCopilot#77]
I'm sorry to bother you.I opened the vscode software, but the Lean language server could not connect successfully. Because the area is restricted. I use a proxy to access the Internet and configure the proxy address on the vscode client. But it still appears that the Lean language server cannot be successfully connected. What should I do?
![屏幕截图 2024-05-27 110955](https://github.com/lean-dojo/LeanCopilot/assets/33314971/cb01af35-cf3d-48a7-b4f4-857a64d910a3)

**Comment by Peiyang-Song** [comment]
Hi @whsm , thanks for the question! According to the description, it seems that your difficulty connecting to Lean is not an issue specific to Lean Copilot. If that is the case, you might want to ask directly in the Lean4 repo for help from a broader community. Hope this helps!

**Comment by whsm** [comment]
I understand and thank you very much for your reply.
