### ISSUE TITLE
unknown package

### ISSUE THREAD

**Issue by jaredgreen2** [lean-dojo/LeanCopilot#85]
I followed the steps in the leancopilot readme immediately after installing lean and dependencies. I have not updated curl.
$ lake update LeanCopilot
warning; Qq: ignoring missing dependency manifest ‘./.lake/packages/Qq/lake-manifest.json’
warning: Cli: ignoring missing dependency manifest ‘./.lake/packages/Cli/lake-manifest.json’
mathlib: running post-update hooks
Warning: recommended ‘curl’ version >=7.70. Found 7.64.1. Can’t use ‘--parallel.’
No files to download
Decompressing 4291 file(s)
unpacked in 72690 ms
$ lean exe LeanCopilot/download
error unknown package ‘LeanCopilot’
$

**Comment by Peiyang-Song** [comment]
Hi @jaredgreen2 , I think the command you would like to run here is `lake exe LeanCopilot/download` instead of `lean exe LeanCopilot/download`.

**Comment by Peiyang-Song** [comment]
Please feel free to reopen the issue if new errors are encountered.

**Comment by Peiyang-Song** [comment]
Hi @jaredgreen2 , can you provide your OS information?

**Comment by jaredgreen2** [comment]
mac os x Catalina 10.15.7

**Comment by Peiyang-Song** [comment]
Thanks. I just tested on my own Mac and wasn't able to reproduce your issue. Did you follow the exact same steps as in `build.sh` or `build_example.sh`? If so, could you provide a [mwe](https://leanprover-community.github.io/mwe.html)?

**Comment by jaredgreen2** [comment]
curl https://raw.githubusercontent.com/leanprover/elan-init.sh -sSf | bash -s -- -y
curl: (22) The requested URL returned error: 400

**Comment by jaredgreen2** [comment]
never mind previous comment

**Comment by jaredgreen2** [comment]
the project im working on is at https://github.com/jaredgreen2/polySat  . i haven't committed anything specific to leancopilot there. i started by cloning that and following the readme.

**Comment by jaredgreen2** [comment]
of course it wasn't in the lake-manifest
