### ISSUE TITLE
How to check each tactic candidate?

### ISSUE THREAD

**Issue by XiaoyangLiu-sjtu** [lean-dojo/LeanCopilot#91]
In your paper about Lean Copilot, I read that: "When applied, it feeds the current goal into an LLM and obtains a list of generated tactic candidates from the LLM. It checks each tactic candidate to see if they (1) lead to errors; (2) result in no errors but cannot finish the proof; (3) successfully finish the proof." 

For the first step of inputting the current goal and generating tactic candidates, I read the relevant implementation steps in ModelAPIs.lean and models.py. 

For the second step about check, I would like to ask in which file it is implemented? I'm interested in this judgment step, any response would be very appreciated.

**Comment by Peiyang-Song** [comment]
Hi @XiaoyangLiu-sjtu , thanks for your interest. The check is part of the frontend, implemented in `LeanCopilot/Frontend.lean`.
